02:30:23 - INFO: Starting epoch 0:
  0%|          | 0/1637 [00:00<?, ?it/s]  0%|          | 0/1637 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/liuzilong/deep-learning-model/DDPM/train.py", line 52, in <module>
    predicted_noise = model(x_t, t, labels)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/liuzilong/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liuzilong/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liuzilong/deep-learning-model/DDPM/model.py", line 192, in forward
    x = self.sa6(x)
        ^^^^^^^^^^^
  File "/home/liuzilong/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liuzilong/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liuzilong/deep-learning-model/DDPM/model.py", line 55, in forward
    attention_value, _ = self.mha(x_ln, x_ln, x_ln)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liuzilong/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liuzilong/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liuzilong/anaconda3/lib/python3.11/site-packages/torch/nn/modules/activation.py", line 1373, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liuzilong/anaconda3/lib/python3.11/site-packages/torch/nn/functional.py", line 6374, in multi_head_attention_forward
    attn_output_weights = softmax(attn_output_weights, dim=-1)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/liuzilong/anaconda3/lib/python3.11/site-packages/torch/nn/functional.py", line 2140, in softmax
    ret = input.softmax(dim)
          ^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.00 GiB. GPU 0 has a total capacity of 23.64 GiB of which 1.25 GiB is free. Process 2242045 has 16.12 GiB memory in use. Including non-PyTorch memory, this process has 6.27 GiB memory in use. Of the allocated memory 5.75 GiB is allocated by PyTorch, and 68.03 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
